name: Publish

on:
    push: 
        branches: 
            - master

env:
    BUILDER: "heroku/builder:22"
    IMG_NAME: 'pet-store'
    USERNAME: "sohelwohlig"

jobs:
    version:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

    dockerhub_remote_build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Set App Name
              run: 'echo "IMG_NAME=$(echo ${USERNAME})/$(echo ${IMG_NAME})" >> $GITHUB_ENV'

            - name: login
              uses: docker/login-action@v1
              with:
                username: ${{ env.USERNAME }}
                password: ${{ secrets.DOCKER_HUB_PASS }}

            - name: Pack Remote Build
              uses: dfreilich/pack-action@v2.1.1
              with:
                  args: 'build ${{ env.IMG_NAME }} --builder ${{ env.BUILDER }} --publish'  

            - name: Test App
              run: |
                  docker run -d -p 3001:3001 --name pet-store ${{ env.IMG_NAME }}
                  sleep 30s
                  curl --request GET --url http://localhost:3001/owners

            - name: Pack Rebase
              uses: dfreilich/pack-action@v2.1.1
              with:
                  args: 
                    'rebase ${{ env.IMG_NAME }}'
            
            - name: Inspect Image
              uses: dfreilich/pack-action@v2.1.1
              with:
                args: 'inspect-image ${{ env.IMG_NAME }}'

            - name: Clean Up
              run: |
                docker container stop 'pet-store'